a = int(input("enter first number: "))
b = int(input("enter second number: "))
print("addition:", a+b)
print("subtraction:", a-b)
print("multiplication:", a*b)
print("division:", a/b)
print("day 13 github workflow peactice")
print("day 13 advanced github practice")
print("day 14 git status practice")
print("day 14 git diff working")
print("day 15 branch practice")